### ISSUE TITLE
Row-wise correction for downgrading dmcx is occurring column-wise

### ISSUE THREAD

**Issue by hlweeks** [patrickmdnet/medicalrisk#2]
In generate_comorbidity_df, for the cases where dmcx is downgraded to dm the code [(here)](https://github.com/patrickmdnet/medicalrisk/blob/master/R/icd9cm.R#L541) is `df[rows, c("dm","dmcx")] <- c(T,F)`. By default, R fills in matrices column-wise when I think you want the replacement to be row-wise.

I've been replacing the code above with `df[rows, c("dm", "dmcx")] <- matrix(rep(c(T,F), length(rows)), byrow = TRUE, ncol = 2)` in the function locally.

Thanks!

**Comment by patrickmdnet** [comment]
Thanks, I will look at that.

**Comment by patrickmdnet** [comment]
repro case:
````r
cases <- data.frame(id=c(1,1,1,1,2,2,2,2,2,2),
icd9cm=c("D1970","D20206","D25071","D4439","D25001","D45621","D570","D25071","D4439","D25070"),
      stringsAsFactors=TRUE)
gen <- generate_comorbidity_df(cases)
gen[,c('dm','dmcx')]

     dm  dmcx
1  TRUE FALSE
2 FALSE  TRUE
````
which is wrong; 2 should be dm=TRUE, dmcx=FALSE.
